services:
  - type: web
    name: fast-email-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main
